import java.io.File

val earthbound = SoundFont2(File("earthbound.sf2"))
val timing = Timing(160.0)
val key = Note.C4.semitones(8).major()
val lead = earthbound[earthbound.presets.indices.random()].gain(0.3)
track(lead) {
    play(key[0], timing.whole)
    rest(timing.eighth)
    play(key[0], timing.eighth)
    play(key[-1], timing.eighth)
    play(key[0], timing.eighth)
    play(key[4], timing.quarter)
    play(key[-1], timing.eighth)
    play(key[0], timing.eighth + timing.whole)
    rest(timing.eighth)
    play(key[0], timing.eighth)
    play(key[-1], timing.eighth)
    play(key[-2], timing.eighth)
    play(key[-3], timing.quarter)
    play(key[-1], timing.quarter)
    play(key[0], timing.eighth)
    play(key[-1], timing.eighth)
    play(key[0], timing.eighth)
    play(key[4], timing.quarter * 1.5)
    play(key[4], timing.eighth)
    play(key[5], timing.eighth)
    play(key[4], timing.quarter)
    play(key[3], timing.eighth)
    play(key[2], timing.quarter * 1.5)
    play(key[0], timing.quarter)
    play(key[1], timing.quarter * 1.5)
    play(key[-2], timing.quarter * 1.5)
    play(key[1], timing.quarter)
    play(key[2], timing.quarter * 1.5)
    play(key[3], timing.sixteenth)
    play(key[2], timing.sixteenth)
    play(key[1], timing.half)
    rest(timing.whole * 3)
}